// Code generated by "stringer -type EzLogLevel"; DO NOT EDIT.

package ezlog

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LOG - -2]
	_ = x[DISABLED - -1]
	_ = x[EMERG-0]
	_ = x[ALERT-1]
	_ = x[CRIT-2]
	_ = x[ERR-3]
	_ = x[WARNING-4]
	_ = x[NOTICE-5]
	_ = x[INFO-6]
	_ = x[DEBUG-7]
	_ = x[TRACE-8]
}

const _EzLogLevel_name = "LOGDISABLEDEMERGALERTCRITERRWARNINGNOTICEINFODEBUGTRACE"

var _EzLogLevel_index = [...]uint8{0, 3, 11, 16, 21, 25, 28, 35, 41, 45, 50, 55}

func (i EzLogLevel) String() string {
	i -= -2
	if i < 0 || i >= EzLogLevel(len(_EzLogLevel_index)-1) {
		return "EzLogLevel(" + strconv.FormatInt(int64(i+-2), 10) + ")"
	}
	return _EzLogLevel_name[_EzLogLevel_index[i]:_EzLogLevel_index[i+1]]
}
