// Code generated by "stringer -type Level"; DO NOT EDIT.

package ezlog

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LogLevel - -2]
	_ = x[Disabled - -1]
	_ = x[EMERG-0]
	_ = x[ALERT-1]
	_ = x[CRIT-2]
	_ = x[ERR-3]
	_ = x[WARNING-4]
	_ = x[NOTICE-5]
	_ = x[INFO-6]
	_ = x[DEBUG-7]
	_ = x[TRACE-8]
}

const _Level_name = "LogLevelDisabledEMERGALERTCRITERRWARNINGNOTICEINFODEBUGTRACE"

var _Level_index = [...]uint8{0, 8, 16, 21, 26, 30, 33, 40, 46, 50, 55, 60}

func (i Level) String() string {
	i -= -2
	if i < 0 || i >= Level(len(_Level_index)-1) {
		return "Level(" + strconv.FormatInt(int64(i+-2), 10) + ")"
	}
	return _Level_name[_Level_index[i]:_Level_index[i+1]]
}
